BEGIN;

CREATE TABLE IF NOT EXISTS public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.study_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT NOT NULL UNIQUE,
    username TEXT NOT NULL UNIQUE,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    role_id BIGINT NOT NULL REFERENCES public.roles(id) ON DELETE RESTRICT,
    study_group_id BIGINT REFERENCES public.study_groups(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.words (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    russian_word TEXT NOT NULL,
    english_translation TEXT NOT NULL,
    transcription TEXT,
    example_sentence TEXT
);

CREATE TABLE IF NOT EXISTS public.vocabulary_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme_name TEXT NOT NULL,
    cefr_level TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.set_words_link (
    vocabulary_set_id BIGINT NOT NULL REFERENCES public.vocabulary_sets(id) ON DELETE CASCADE,
    word_id BIGINT NOT NULL REFERENCES public.words(id) ON DELETE CASCADE,
    PRIMARY KEY (vocabulary_set_id, word_id)
);

CREATE TABLE IF NOT EXISTS public.tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deadline TIMESTAMPTZ,
    start_date TIMESTAMPTZ,
    translate_to_russian BOOLEAN NOT NULL DEFAULT true,
    available_after_end BOOLEAN NOT NULL DEFAULT false,
    attempts_count INTEGER NOT NULL DEFAULT 1 CHECK (attempts_count > 0),
    vocabulary_set_id BIGINT NOT NULL REFERENCES public.vocabulary_sets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.task_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_id BIGINT NOT NULL REFERENCES public.statuses(id) ON DELETE RESTRICT,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    task_id BIGINT NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    task_execution_id BIGINT NOT NULL REFERENCES public.task_executions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.question_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entered_answer TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL,
    attempt_id BIGINT NOT NULL REFERENCES public.attempts(id) ON DELETE CASCADE,
    word_id BIGINT NOT NULL REFERENCES public.words(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    type TEXT NOT NULL,
    text TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notification_users_link (
    notification_id BIGINT NOT NULL REFERENCES public.notifications(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    PRIMARY KEY (notification_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    condition_text TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.user_achievements_link (
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    achievement_id BIGINT NOT NULL REFERENCES public.achievements(id) ON DELETE CASCADE,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, achievement_id)
);

CREATE INDEX IF NOT EXISTS idx_users_role_id ON public.users(role_id);
CREATE INDEX IF NOT EXISTS idx_users_study_group_id ON public.users(study_group_id);
CREATE INDEX IF NOT EXISTS idx_vocabulary_sets_user_id ON public.vocabulary_sets(user_id);
CREATE INDEX IF NOT EXISTS idx_set_words_link_word_id ON public.set_words_link(word_id);
CREATE INDEX IF NOT EXISTS idx_tasks_vocabulary_set_id ON public.tasks(vocabulary_set_id);
CREATE INDEX IF NOT EXISTS idx_task_executions_status_id ON public.task_executions(status_id);
CREATE INDEX IF NOT EXISTS idx_task_executions_user_id ON public.task_executions(user_id);
CREATE INDEX IF NOT EXISTS idx_task_executions_task_id ON public.task_executions(task_id);
CREATE INDEX IF NOT EXISTS idx_attempts_task_execution_id ON public.attempts(task_execution_id);
CREATE INDEX IF NOT EXISTS idx_question_answers_attempt_id ON public.question_answers(attempt_id);
CREATE INDEX IF NOT EXISTS idx_question_answers_word_id ON public.question_answers(word_id);
CREATE INDEX IF NOT EXISTS idx_notification_users_link_user_id ON public.notification_users_link(user_id);
CREATE INDEX IF NOT EXISTS idx_user_achievements_link_achievement_id ON public.user_achievements_link(achievement_id);

COMMIT;
